# Generated by Django 4.1.5 on 2023-01-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shopy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pub_date",
        ),
    ]
